/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sciJava.catalogs

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

/**
 * A simple 'hello world' plugin.
 */
class SciJavaCatalogsPlugin : Plugin<Settings> {

    override fun apply(settings: Settings) {

        // Register a task
        //        project.tasks.register("greeting") { task ->
        //            task.doLast {
        //                println("Hello from plugin 'sciJava.catalogs.greeting'")
        //            }
        //        }

        settings.dependencyResolutionManagement.versionCatalogs.apply {

            /*


                                    <!-- Google Cloud Storage - https://github.com/googleapis/google-cloud-java -->
                                    <google-cloud-nio.version>0.120.0-alpha</google-cloud-nio.version>
                                    <google-cloud-resourcemanager.version>0.117.2-alpha</google-cloud-resourcemanager.version>
                                    <google-cloud-storage.version>1.108.0</google-cloud-storage.version>

                                    <!-- Gson - https://code.google.com/p/google-gson/ -->
                                    <gson.version>2.8.6</gson.version>

                                    <!-- Guava - https://github.com/google/guava -->
                                    <guava.version>21.0</guava.version>

                                    <!-- HyperSQL DataBase - http://hsqldb.org/ -->
                                    <hsqldb.version>1.8.0.10</hsqldb.version>

                                    <!-- iText PDF - https://github.com/itext/itextpdf -->
                                    <itextpdf.version>5.5.13.1</itextpdf.version>

                                    <!-- Jackrabbit WebDAV - https://jackrabbit.apache.org/jcr/components/jackrabbit-webdav-library.html -->
                                    <jackrabbit-webdav.version>2.21.1</jackrabbit-webdav.version>

                                    <!-- Jackson - https://github.com/FasterXML/jackson -->
                                    <jackson-databind.version>2.11.0</jackson-databind.version>

                                    <!-- Java Advanced Imaging - https://java.net/projects/jai-core -->
                                    <jai.version>1.1.3</jai.version>
                                    <jai-codec.version>${jai.version}</jai-codec.version>
                                    <jai-core.version>${jai.version}</jai-core.version>

                                    <!-- JAMA - https://math.nist.gov/javanumerics/jama/ -->
                                    <jama.version>1.0.3</jama.version>

                                    <!-- Java 3D - https://github.com/scijava/java3d-core -->
                                    <java3d.version>1.6.0-scijava-2</java3d.version>
                                    <j3dcore.version>${java3d.version}</j3dcore.version>
                                    <j3dutils.version>${java3d.version}</j3dutils.version>
                                    <vecmath.version>${java3d.version}</vecmath.version>

                                    <!-- Javassist - https://www.javassist.org/ -->
                                    <javassist.version>3.27.0-GA</javassist.version>

                                    <!-- JDOM - http://www.jdom.org/ -->
                                    <jdom2.version>2.0.6</jdom2.version>

                                    <!-- Java Expression Parser - https://github.com/scijava/jep -->
                                    <jep.version>2.4.2</jep.version>

                                    <!-- Jetty - https://www.eclipse.org/jetty/ -->
                                    <jetty.version>9.4.29.v20200521</jetty.version>
                                    <jetty-annotations.version>${jetty.version}</jetty-annotations.version>
                                    <!--
                                NB: We do not manage jetty-ant. It depends on ant with old groupId (ant),
                                    which conflicts with other dependencies using new groupId (org.apache.ant).
                                    -->
                                    <jetty-client.version>${jetty.version}</jetty-client.version>
                                    <jetty-continuation.version>${jetty.version}</jetty-continuation.version>
                                    <jetty-deploy.version>${jetty.version}</jetty-deploy.version>
                                    <jetty-http.version>${jetty.version}</jetty-http.version>
                                    <jetty-http-spi.version>${jetty.version}</jetty-http-spi.version>
                                    <jetty-io.version>${jetty.version}</jetty-io.version>
                                    <jetty-jaas.version>${jetty.version}</jetty-jaas.version>
                                    <jetty-jaspi.version>${jetty.version}</jetty-jaspi.version>
                                    <jetty-jmx.version>${jetty.version}</jetty-jmx.version>
                                    <jetty-jndi.version>${jetty.version}</jetty-jndi.version>
                                    <!--
                                NB: We do not manage jetty-jspc-maven-plugin or jetty-maven-plugin.
                                    Their dependencies include several artifacts conflicting with elsewhere:
                                    * classworlds:classworlds vs. org.codehaus.plexus:plexus-classworlds
                                    * javax.annotation:jsr250-api vs. javax.annotation:javax.annotation-api
                                    * javax.websocket:javax.websocket-api vs. javax.websocket:javax.websocket-client-api
                                    * org.mortbay.jasper:apache-el vs. javax.el:javax.el-api
                                    -->
                                    <jetty-nosql.version>${jetty.version}</jetty-nosql.version>
                                    <jetty-plus.version>${jetty.version}</jetty-plus.version>
                                    <jetty-proxy.version>${jetty.version}</jetty-proxy.version>
                                    <jetty-rewrite.version>${jetty.version}</jetty-rewrite.version>
                                    <!-- NB: We do not manage jetty-runner. It is an unshaded uber-JAR. -->
                                    <jetty-security.version>${jetty.version}</jetty-security.version>
                                    <jetty-server.version>${jetty.version}</jetty-server.version>
                                    <jetty-servlet.version>${jetty.version}</jetty-servlet.version>
                                    <jetty-servlets.version>${jetty.version}</jetty-servlets.version>
                                    <jetty-spring.version>${jetty.version}</jetty-spring.version>
                                    <jetty-start.version>${jetty.version}</jetty-start.version>
                                    <jetty-util.version>${jetty.version}</jetty-util.version>
                                    <jetty-util-ajax.version>${jetty.version}</jetty-util-ajax.version>
                                    <jetty-webapp.version>${jetty.version}</jetty-webapp.version>
                                    <jetty-xml.version>${jetty.version}</jetty-xml.version>

                                    <!-- JFreeChart - http://www.jfree.org/jfreechart/ -->
                                    <jfreechart.version>1.5.0</jfreechart.version>

                                    <!-- JFreeSVG - http://www.jfree.org/jfreesvg/ -->
                                    <jfreesvg.version>3.4</jfreesvg.version>

                                    <!-- JGraphT - https://github.com/jgrapht/jgrapht -->
                                    <jgrapht.version>1.4.0</jgrapht.version>
                                    <jgrapht-core.version>${jgrapht.version}</jgrapht-core.version>
                                    <jgrapht-demo.version>${jgrapht.version}</jgrapht-demo.version>
                                    <jgrapht-ext.version>${jgrapht.version}</jgrapht-ext.version>
                                    <jgrapht-guava.version>${jgrapht.version}</jgrapht-guava.version>
                                    <jgrapht-io.version>${jgrapht.version}</jgrapht-io.version>
                                    <jgrapht-opt.version>${jgrapht.version}</jgrapht-opt.version>

                                    <!-- JGraphX - https://github.com/jgraph/jgraphx -->
                                    <jgraphx.version>4.1.0</jgraphx.version>

                                    <!-- JHDF5 - https://wiki-bsse.ethz.ch/label/JHDF5/hdf5 -->
                                    <jhdf5.version>14.12.6</jhdf5.version>

                                    <!-- JMH - https://openjdk.java.net/projects/code-tools/jmh/ -->
                                    <jmh.version>1.23</jmh.version>
                                    <jmh-core.version>${jmh.version}</jmh-core.version>
                                    <jmh-generator-annprocess.version>${jmh.version}</jmh-generator-annprocess.version>

                                    <!-- JMockit - https://jmockit.github.io/ -->
                                    <jmockit.version>1.49</jmockit.version>

                                    <!-- JNA - https://github.com/twall/jna -->
                                    <jna.version>4.5.2</jna.version>

                                    <!-- Joda-Time - https://www.joda.org/joda-time/ -->
                                    <joda-time.version>2.10.6</joda-time.version>

                                                    <!-- JPedal - http://jpedal.org/ (defunct) -->
                                                    <jpedal.version>2.80b11</jpedal.version>
                                                    <jpedalSTD.version>${jpedal.version}</jpedalSTD.version>

                                                    <!-- JSch - http://www.jcraft.com/jsch/ -->
                                                    <jsch.version>0.1.55</jsch.version>

                                                    <!-- JUnit 5 - https://junit.org/junit5/ -->
                                                    <junit-jupiter.version>5.6.2</junit-jupiter.version>
                                                    <junit-jupiter-api.version>${junit-jupiter.version}</junit-jupiter-api.version>
                                                    <junit-jupiter-engine.version>${junit-jupiter.version}</junit-jupiter-engine.version>
                                                    <junit-jupiter-migrationsupport.version>${junit-jupiter.version}</junit-jupiter-migrationsupport.version>
                                                    <junit-jupiter-params.version>${junit-jupiter.version}</junit-jupiter-params.version>
                                                    <junit-vintage-engine.version>${junit-jupiter.version}</junit-vintage-engine.version>

                                                    <!-- Jython - https://jython.org/ -->
                                                    <jython.version>2.7.2</jython.version>
                                                    <jython-slim.version>${jython.version}</jython-slim.version>

                                                    <!-- JZlib - http://www.jcraft.com/jzlib/ -->
                                                    <jzlib.version>1.1.3</jzlib.version>

                                                    <!-- Kotlin - https://kotlinlang.org/ -->
                                                    <!-- NB: kotlin.version is defined in pom-scijava-base. -->
                                                    <kotlin-compiler-embeddable.version>${kotlin.version}</kotlin-compiler-embeddable.version>
                                                    <kotlin-daemon-embeddable.version>${kotlin.version}</kotlin-daemon-embeddable.version>
                                                    <kotlin-reflect.version>${kotlin.version}</kotlin-reflect.version>
                                                    <kotlin-script-runtime.version>${kotlin.version}</kotlin-script-runtime.version>
                                                    <kotlin-script-util.version>${kotlin.version}</kotlin-script-util.version>
                                                    <kotlin-scripting-common.version>${kotlin.version}</kotlin-scripting-common.version>
                                                    <kotlin-scripting-compiler-embeddable.version>${kotlin.version}</kotlin-scripting-compiler-embeddable.version>
                                                    <kotlin-scripting-jvm.version>${kotlin.version}</kotlin-scripting-jvm.version>
                                                    <kotlin-stdlib.version>${kotlin.version}</kotlin-stdlib.version>
                                                    <kotlin-stdlib-common.version>${kotlin.version}</kotlin-stdlib-common.version>
                                                    <kotlin-stdlib-jdk8.version>${kotlin.version}</kotlin-stdlib-jdk8.version>


                                                    <!-- Logback - https://logback.qos.ch/ -->
                                                    <logback.version>1.2.3</logback.version>
                                                    <logback-classic.version>${logback.version}</logback-classic.version>
                                                    <logback-core.version>${logback.version}</logback-core.version>

                                                    <!-- LZ4 compression for Java - https://github.com/lz4/lz4-java -->
                                                    <lz4-java.version>1.7.1</lz4-java.version>

                                                    <!-- MapDB - https://www.mapdb.org/ -->
                                                    <mapdb.version>3.0.8</mapdb.version>

                                                    <!-- MigLayout - http://www.miglayout.com/ -->
                                                    <miglayout.version>5.2</miglayout.version>
                                                    <miglayout-core.version>${miglayout.version}</miglayout-core.version>
                                                    <miglayout-swing.version>${miglayout.version}</miglayout-swing.version>
                                                    <miglayout-swt.version>${miglayout.version}</miglayout-swt.version>

                                                    <!-- Mines JTK - https://github.com/dhale/jtk -->
                                                    <mines-jtk.version>20151125</mines-jtk.version>

                                                    <!-- Mockito - https://site.mockito.org/ -->
                                                    <mockito.version>2.19.0</mockito.version>
                                                    <mockito-core.version>${mockito.version}</mockito-core.version>

                                                    <!-- oj! Algorithms - https://github.com/optimatika/ojAlgo -->
                                                    <ojalgo.version>45.1.1</ojalgo.version>

                                                    <!-- OpenCSV - http://opencsv.sourceforge.net/ -->
                                                    <opencsv.version>5.2</opencsv.version>

                                                    <!-- picocli - https://picocli.info/ -->
                                                    <picocli.version>4.3.2</picocli.version>

                                                    <!-- PostgreSQL JDBC Driver - https://jdbc.postgresql.org/ -->
                                                    <postgresql.version>42.2.12</postgresql.version>

                                                    <!-- RSyntaxTextArea - https://bobbylight.github.io/RSyntaxTextArea/ -->
                                                    <rsyntaxtextarea.version>3.1.1</rsyntaxtextarea.version>
                                                    <autocomplete.version>3.1.0</autocomplete.version>
                                                    <languagesupport.version>3.1.0</languagesupport.version>

                                                    <!-- SnakeYAML - https://bitbucket.org/asomov/snakeyaml -->
                                                    <snakeyaml.version>1.26</snakeyaml.version>

                                                    <!-- SnakeYAML Engine - https://bitbucket.org/asomov/snakeyaml-engine -->
                                                    <snakeyaml-engine.version>2.1</snakeyaml-engine.version>

                                                    <!-- Spring - https://spring.io/ -->
                                                    <!--
                                                NB: 3.2.9.RELEASE is the last version not to depend properly on
                                                    aopalliance:aopalliance, rather than including org.aopalliance
                                                    classes unshadowed!
                                                    -->
                                                    <spring-aop.version>3.2.9.RELEASE</spring-aop.version>

                                                    <!-- TensorFlow - https://www.tensorflow.org/ -->
                                                    <tensorflow.version>1.12.0</tensorflow.version>
                                                    <libtensorflow.version>${tensorflow.version}</libtensorflow.version>
                                                    <libtensorflow_jni.version>${tensorflow.version}</libtensorflow_jni.version>
                                                    <libtensorflow_jni_gpu.version>${tensorflow.version}</libtensorflow_jni_gpu.version>
                                                    <proto.version>${tensorflow.version}</proto.version>

                                                    <!-- Trove - http://trove.starlight-systems.com/ -->
                                                    <trove4j.version>3.0.3</trove4j.version>

                                                    <!-- Weka - https://www.cs.waikato.ac.nz/ml/weka/ -->
                                                    <weka.version>3.9.4</weka.version>
                                                    <weka-dev.version>${weka.version}</weka-dev.version>

                                                    <!-- XZ for Java - https://tukaani.org/xz/java.html -->
                                                    <xz.version>1.8</xz.version>
                                                    </properties>

                                                    <dependencyManagement>
                                                    <dependencies>*/

            // SciJava - https://github.com/scijava
            addSciJava()

            // ImageJ - https://github.com/imagej
            addImagej()

            // ImgLib2 - https://github.com/imglib
            addImgLib2()

            // SCIFIO - https://github.com/scifio
            addScifio()

            // Standard Fiji projects
            addFiji()

            create("misc").apply {

                // External Fiji projects

                // SNT - https://github.com/morphonets/SNT
                alias("snt").to("org.morphonets:SNT:3.1.112")

                // JITK TPS - https://github.com/saalfeldlab/jitk-tps
                alias("jitkTps").to("jitk:jitk-tps:3.0.1")

                // BigWarp - https://github.com/saalfeldlab/bigwarp
                alias("bigwarpFiji").to("sc.fiji:bigwarp_fiji:6.0.0")

                // MPI-CBG - https://github.com/axtimwalde/mpicbg
                alias("mpicbg").to("mpicbg:mpicbg:1.4.1")

                // TrakEM2 TPS - https://github.com/saalfeldlab/trakem2-tps
                alias("trakem2Tps").to("sc.fiji:trakem2_tps:1.1.4")

                // Z-Spacing correction - https://github.com/saalfeldlab/z-spacing
                alias("zSpacing").to("sc.fiji:z_spacing:1.1.1")

                // BigDataViewer - https://github.com/bigdataviewer
                create("bigDataViewer").apply {
                    alias("core").to("sc.fiji:bigdataviewer-core:9.0.6")
                    alias("server").to("sc.fiji:bigdataviewer-server:3.0.0")
                    alias("visTools").to("sc.fiji:bigdataviewer-vistools:1.0.0-beta-21")
                    alias("fiji").to("sc.fiji:bigdataviewer_fiji:6.2.0")
                    alias("spimData").to("sc.fiji:spim_data:2.2.4")
                }

                // TrakEM2 - https://github.com/trakem2
                create("trakEM2").apply {
                    alias("nit").to("sc.fiji:T2-NIT:1.1.3")
                    alias("treeLineGraph").to("sc.fiji:T2-TreelineGraph:1.1.3")
                    alias("core").to("sc.fiji:TrakEM2_:1.3.4")
                    alias("vectorString").to("sc.fiji:VectorString:2.0.2")
                    alias("transform").to("sc.fiji:trakem2-transform:1.0.1")
                }

                // N5 - https://github.com/saalfeldlab/n5
                create("n5").apply {
                    alias("labelMultisets").to("net.imglib2:imglib2-label-multisets:0.9.0")
                    alias("core").to("org.janelia.saalfeldlab:n5:2.2.1")
                    alias("awsS3").to("org.janelia.saalfeldlab:n5-aws-s3:3.1.3")
                    alias("blosc").to("org.janelia.saalfeldlab:n5-blosc:1.1.0")
                    alias("googleCloud").to("org.janelia.saalfeldlab:n5-google-cloud:3.2.2")
                    alias("hdf5").to("org.janelia.saalfeldlab:n5-hdf5:1.1.0")
                    alias("imglib2").to("org.janelia.saalfeldlab:n5-imglib2:3.5.1")
                    alias("viewerFiji").to("org.janelia.saalfeldlab:n5-viewer_fiji:2.2.0")
                    alias("zarr").to("org.janelia.saalfeldlab:n5-zarr:0.0.4")
                }

                // BoneJ - http://bonej.org/
                create("boneJ").apply {
                    val version = "7.0.7"
                    alias("plugins").to("org.bonej:bonej-plugins:$version")
                    alias("ops").to("org.bonej:bonej-ops:$version")
                    alias("legacyPlugins").to("org.bonej:bonej-legacy-plugins_:$version")
                    alias("legacyUtil").to("org.bonej:bonej-legacy-util_:$version")
                    alias("utilities").to("org.bonej:bonej-utilities:$version")
                }

                // Open Microscopy Environment - https://github.com/ome
                create("ome").apply {

                    // Metakit - https://github.com/ome/ome-metakit
                    alias("metakit").to("org.openmicroscopy:metakit:5.3.2")

                    // OME Common Java - https://github.com/ome/ome-common-java
                    alias("common").to("org.openmicroscopy:ome-common:6.0.4")

                    // OME POI - https://github.com/ome/ome-poi
                    alias("poi").to("org.openmicroscopy:ome-poi:5.3.3")

                    // OME Model - https://github.com/ome/ome-model
                    alias("xml").to("org.openmicroscopy:ome-xml:6.1.0")

                    // Glencoe Software jxrlib - https://github.com/glencoesoftware/jxrlib
                    alias("jxrlibAll").to("ome:jxrlib-all:0.2.4")

                    // Bio-Formats - https://github.com/ome/bioformats
                    val version = "6.5.1"
                    alias("bioFormatsPlugins").to("ome:bio-formats_plugins:$version")
                    alias("formatsApi").to("ome:formats-api:$version")
                    alias("formatsBsd").to("ome:formats-bsd:$version")
                    alias("formatsGpl").to("ome:formats-gpl:$version")
                }

                create("omero").apply {

                    // OMERO Blitz - https://github.com/ome/omero-blitz
                    alias("blitz").to("org.openmicroscopy:omero-blitz:5.5.6")

                    // OMERO Common - https://github.com/ome/omero-common
                    alias("common").to("org.openmicroscopy:omero-common:5.5.5")

                    // OMERO DSL Plugin - https://github.com/ome/omero-dsl-plugin
                    alias("dslPlugin").to("org.openmicroscopy:omero-dsl-plugin:5.5.0")

                    // OMERO Gateway - https://github.com/ome/omero-gateway-java
                    alias("gateway").to("org.openmicroscopy:omero-gateway:5.6.3")

                    // OMERO Model - https://github.com/ome/omero-model
                    alias("model").to("org.openmicroscopy:omero-model:5.6.0")

                    // OMERO Renderer - https://github.com/ome/omero-renderer
                    alias("renderer").to("org.openmicroscopy:omero-renderer:5.5.5")

                    // OMERO ROMIO - https://github.com/ome/omero-romio
                    alias("romio").to("org.openmicroscopy:omero-romio:5.6.0")

                    // OMERO Server - https://github.com/ome/omero-server
                    alias("server").to("org.openmicroscopy:omero-server:5.5.6")
                }

                // Other SciJava components

                // MorphoLibJ - https://github.com/ijpb/MorphoLibJ
                alias("morphoLibJ").to("fr.inra.ijpb:MorphoLibJ_:1.4.2.1")

                // BigStitcher - https://github.com/PreibischLab/BigStitcher
                alias("bigStitcher").to("net.preibisch:BigStitcher:0.5.8")

                // multiview-reconstruction - https://github.com/PreibischLab/multiview-reconstruction
                alias("multiviewReconstruction").to("net.preibisch:multiview-reconstruction:0.7.2")

                // multiview-simulation - https://github.com/PreibischLab/multiview-simulation
                alias("multiviewSimulation").to("net.preibisch:multiview-simulation:0.2.0")

                // CoreMem - https://github.com/ClearControl/CoreMem
                alias("coreMem").to("net.clearcontrol:coremem:0.4.8")

                // ClearGL - https://github.com/ClearVolume/ClearGL
                alias("cleargl").to("net.clearvolume:cleargl:2.2.10")

                // Scenery - https://github.com/scenerygraphics/scenery
                alias("scenery").to("graphics.scenery:scenery:0.7.0-beta-7")

                // SciView - https://github.com/scenerygraphics/SciView
                alias("sciview").to("sc.iview:sciview:0.2.0-beta-5")

                // Third party components

                // Amazon S3 - https://aws.amazon.com/sdkforjava
                alias("awsJdkS3").to("com.amazonaws:aws-java-sdk-s3:1.11.796")

                // Apache Groovy - https://groovy-lang.org/
                create("groovy").apply {
                    val version = "3.0.4"
                    val root = "org.codehaus.groovy:groovy"
                    alias("core").to("$root:$version")
                    alias("ant").to("$root-ant:$version")
                    alias("astBuilder").to("$root-astbuilder:$version")
                    alias("bsf").to("$root-bsf:$version")
                    alias("cliCommons").to("$root-cli-commons:$version")
                    alias("cliPicocli").to("$root-cli-picocli:$version")
                    alias("console").to("$root-console:$version")
                    alias("datetime").to("$root-datetime:$version")
                    alias("docgenerator").to("$root-docgenerator:$version")
                    alias("doc").to("$root-groovydoc:$version")
                    alias("sh").to("$root-groovysh:$version")
                    alias("jaxb").to("$root-jaxb:$version")
                    alias("jmx").to("$root-jmx:$version")
                    alias("json").to("$root-json:$version")
                    alias("macro").to("$root-macro:$version")
                    alias("nio").to("$root-nio:$version")
                    alias("servlet").to("$root-servlet:$version")
                    alias("sql").to("$root-sql:$version")
                    alias("templates").to("$root-templates:$version")
                    alias("test").to("$root-test:$version")
                    alias("testJunit5").to("$root-test-junit5:$version")
                    alias("testNg").to("$root-testng:$version")
                    alias("xml").to("$root-xml:$version")
                    alias("yaml").to("$root-yaml:$version")
                }


                create("apache").apply {

                    // Apache Maven - https://maven.apache.org/

                    alias("mavenArtifactTransfer").to("org.apache.maven.shared:maven-artifact-transfer:0.12.0")
                    alias("mavenCommonArtifactFilters").to("org.apache.maven.shared:maven-common-artifact-filters:3.1.0")
                    alias("mavenCore").to("org.apache.maven:maven-core:3.6.3")
                    alias("mavenPluginsToolsApi").to("org.apache.maven.plugin-tools:maven-plugin-tools-api:3.6.0")
                    alias("sisuInjectBean").to("org.sonatype.sisu:sisu-inject-bean:2.6.0")
                    alias("sisuInjectPlexus").to("org.sonatype.sisu:sisu-inject-plexus:2.6.0")

                    // Apache POI - https://poi.apache.org/
                    alias("poi").to("org.apache.poi:poi:3.17")

                    // Apache Spark - https://spark.apache.org/
                    alias("spark").to("org.apache.spark:spark-core_2.11:2.3.1")

                    // Apache HTTPComponents - https://hc.apache.org/
                    alias("httpClient").to("org.apache.httpcomponents:httpclient:4.5.12")
                    alias("httpCore").to("org.apache.httpcomponents:httpcore:4.4.13")
                }

                // Batik - https://xmlgraphics.apache.org/batik/
                create("batik").apply {
                    val version = "1.13"
                    val root = "org.apache.xmlgraphics:batik"
                    alias("anim").to("$root-anim:$version")
                    alias("awtUtil").to("$root-awt-util:$version")
                    alias("bridge").to("$root-bridge:$version")
                    alias("codec").to("$root-codec:$version")
                    alias("constants_").to("$root-costants:$version")
                    //                    alias("css").to("$root-css:$version")
                    alias("dom").to("$root-dom:$version")
                    //                    alias("ext").to("$root-ext:$version")
                    //                    alias("extensions").to("$root-extentions:$version")
                    alias("guiUtil").to("$root-gui-util:$version")
                    alias("gvt").to("$root-gvt:$version")
                    alias("i18n").to("$root-i18n:$version")
                    alias("parser").to("$root-parser:$version")
                    alias("rasterizer").to("$root-rasterizer:$version")
                    alias("rasterizerExt").to("$root-rasterizer-ext:$version")
                    alias("script").to("$root-script:$version")
                    alias("slideshow").to("$root-slideshow:$version")
                    alias("squiggle").to("$root-squiggle:$version")
                    alias("squiggleExt").to("$root-squiggle-ext:$version")
                    alias("svgDom").to("$root-svg-dom:$version")
                    alias("svgGen").to("$root-svggen:$version")
                    alias("svgPP").to("$root-svgpp:$version")
                    alias("swing").to("$root-swing:$version")
                    alias("transcoder").to("$root-transcoder:$version")
                    alias("ttf2svg").to("$root-ttf2svg:$version")
                    alias("util").to("$root-util:$version")
                    alias("xml").to("$root-xml:$version")
                    alias("common").to("org.apache.xmlgraphics:xmlgraphics-commons:2.4")
                }

                // Blosc - https://blosc.org/
                alias("jblosc").to("org.lasersonlab:jblosc:1.0.1")

                // CDI - http://cdi-spec.org/
                alias("cdi").to("javax.enterprise:cdi-api:1.2")

                create("commons").apply {
                    // Commons BeanUtils - https://commons.apache.org/proper/commons-beanutils/
                    alias("beanutils").to("commons-beanutils:commons-beanutils:1.9.4")
                    // Commons Codec - https://commons.apache.org/proper/commons-codec/
                    alias("codec").to("commons-codec:commons-codec:1.14")

                    // Commons Collections - https://commons.apache.org/proper/commons-collections/
                    alias("collections").to("commons-collections:commons-collections:3.2.2")

                    // Commons Compress - https://commons.apache.org/proper/commons-compress/
                    alias("compress").to("org.apache.commons:commons-compress:1.20")

                    // Commons IO - https://commons.apache.org/proper/commons-io/
                    alias("io").to("commons-io:commons-io:2.7")

                    // Commons Lang - https://commons.apache.org/proper/commons-lang/
                    alias("lang").to("commons-lang:commons-lang:2.6")
                    alias("lang3").to("commons-lang:commons-lang3:3.10")

                    // Commons Logging - https://commons.apache.org/proper/commons-logging/
                    alias("logging").to("commons-logging:commons-logging:1.2")

                    // Commons Math - https://commons.apache.org/proper/commons-math/
                    alias("math3").to("org.apache.commons:commons-math3:3.6.1")

                    // Commons Text - https://commons.apache.org/proper/commons-text/
                    alias("text").to("org.apache.commons:commons-text:1.8")
                }

                // Byte Code Generation Library - https://github.com/cglib/cglib
                alias("cglib").to("cglib:cglib:3.3.0")

                // Eclipse Collections - https://www.eclipse.org/collections/
                create("eclipseCollections").apply {
                    val version = "10.4.0"
                    val root = "org.eclipse.collections:eclipse-collections"
                    alias("core").to("$root:$version")
                    alias("api").to("$root-api:$version")
                    alias("forkjoin").to("$root-forkjoin:$version")
                    alias("testutils").to("$root-testutils:$version")
                }
                // Eclipse SWT - https://www.eclipse.org/swt/
                create("eclipseSwt").apply {
                    val version = "4.3"
                    val root = "org.eclipse.swt:org.eclipse.swt"
                    alias("cocoaMacosx").to("$root.cocoa.macosx:$version")
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.cocoa.macosx.x86_64</artifactId>
                    //            <version>${org.eclipse.swt.cocoa.macosx.x86_64.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.aix.ppc</artifactId>
                    //            <version>${org.eclipse.swt.gtk.aix.ppc.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.aix.ppc64</artifactId>
                    //            <version>${org.eclipse.swt.gtk.aix.ppc64.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.hpux.ia64</artifactId>
                    //            <version>${org.eclipse.swt.gtk.hpux.ia64.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.linux.ppc</artifactId>
                    //            <version>${org.eclipse.swt.gtk.linux.ppc.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.linux.ppc64</artifactId>
                    //            <version>${org.eclipse.swt.gtk.linux.ppc64.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.linux.s390</artifactId>
                    //            <version>${org.eclipse.swt.gtk.linux.s390.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.linux.s390x</artifactId>
                    //            <version>${org.eclipse.swt.gtk.linux.s390x.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.linux.x86</artifactId>
                    //            <version>${org.eclipse.swt.gtk.linux.x86.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.linux.x86_64</artifactId>
                    //            <version>${org.eclipse.swt.gtk.linux.x86_64.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.solaris.sparc</artifactId>
                    //            <version>${org.eclipse.swt.gtk.solaris.sparc.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.gtk.solaris.x86</artifactId>
                    //            <version>${org.eclipse.swt.gtk.solaris.x86.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.win32.win32.x86</artifactId>
                    //            <version>${org.eclipse.swt.win32.win32.x86.version}</version>
                    //            </dependency>
                    //            <dependency>
                    //            <groupId>org.eclipse.swt</groupId>
                    //            <artifactId>org.eclipse.swt.win32.win32.x86_64</artifactId>
                    //            <version>${org.eclipse.swt.win32.win32.x86_64.version}</version>
                    //            </dependency>
                }
                //            <!-- Google Cloud Storage - https://github.com/googleapis/google-cloud-java -->
                //            <dependency>
                //            <groupId>com.google.cloud</groupId>
                //            <artifactId>google-cloud-nio</artifactId>
                //            <version>${google-cloud-nio.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>com.google.cloud</groupId>
                //            <artifactId>google-cloud-resourcemanager</artifactId>
                //            <version>${google-cloud-resourcemanager.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>com.google.cloud</groupId>
                //            <artifactId>google-cloud-storage</artifactId>
                //            <version>${google-cloud-storage.version}</version>
                //            </dependency>
                //
                //            <!-- Gson - https://code.google.com/p/google-gson/ -->
                //            <dependency>
                //            <groupId>com.google.code.gson</groupId>
                //            <artifactId>gson</artifactId>
                //            <version>${gson.version}</version>
                //            </dependency>
                //
                //            <!-- Guava - https://github.com/google/guava -->
                //            <dependency>
                //            <groupId>com.google.guava</groupId>
                //            <artifactId>guava</artifactId>
                //            <version>${guava.version}</version>
                //            </dependency>
                //
                //            <!-- HyperSQL DataBase - http://hsqldb.org/ -->
                //            <dependency>
                //            <groupId>hsqldb</groupId>
                //            <artifactId>hsqldb</artifactId>
                //            <version>${hsqldb.version}</version>
                //            </dependency>
                //
                //            <!-- iText PDF - https://github.com/itext/itextpdf -->
                //            <dependency>
                //            <groupId>com.itextpdf</groupId>
                //            <artifactId>itextpdf</artifactId>
                //            <version>${itextpdf.version}</version>
                //            </dependency>
                //
                //            <!-- Jackrabbit WebDAV - https://jackrabbit.apache.org/jcr/components/jackrabbit-webdav-library.html -->
                //            <dependency>
                //            <groupId>org.apache.jackrabbit</groupId>
                //            <artifactId>jackrabbit-webdav</artifactId>
                //            <version>${jackrabbit-webdav.version}</version>
                //            <exclusions>
                //            <exclusion>
                //            <!--
                //        Conflicts with commons-logging:commons-logging.
                //            If you depend on jackrabbit-webdav, add either
                //            commons-logging or jcl-over-slfj to your deps.
                //            See: http://www.slf4j.org/legacy.html#jcl-over-slf4j
                //            -->
                //            <groupId>org.slf4j</groupId>
                //            <artifactId>jcl-over-slf4j</artifactId>
                //            </exclusion>
                //            </exclusions>
                //            </dependency>
                //
                //            <!-- Jackson - https://github.com/FasterXML/jackson -->
                //            <dependency>
                //            <groupId>com.fasterxml.jackson.core</groupId>
                //            <artifactId>jackson-databind</artifactId>
                //            <version>${jackson-databind.version}</version>
                //            </dependency>
                //
                //            <!-- Java Advanced Imaging - https://java.net/projects/jai-core -->
                //            <dependency>
                //            <groupId>com.sun.media</groupId>
                //            <artifactId>jai-codec</artifactId>
                //            <version>${jai-codec.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>javax.media</groupId>
                //            <artifactId>jai-core</artifactId>
                //            <version>${jai-core.version}</version>
                //            </dependency>
                //
                //            <!-- JAMA - http://math.nist.gov/javanumerics/jama/ -->
                //            <dependency>
                //            <groupId>gov.nist.math</groupId>
                //            <artifactId>jama</artifactId>
                //            <version>${jama.version}</version>
                //            </dependency>
                //
                //            <!-- Java 3D - https://github.com/scijava/java3d-core -->
                //            <dependency>
                //            <groupId>org.scijava</groupId>
                //            <artifactId>j3dcore</artifactId>
                //            <version>${j3dcore.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.scijava</groupId>
                //            <artifactId>j3dutils</artifactId>
                //            <version>${j3dutils.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.scijava</groupId>
                //            <artifactId>vecmath</artifactId>
                //            <version>${vecmath.version}</version>
                //            </dependency>
                //
                //            <!-- Javassist - http://www.javassist.org/ -->
                //            <dependency>
                //            <groupId>org.javassist</groupId>
                //            <artifactId>javassist</artifactId>
                //            <version>${javassist.version}</version>
                //            </dependency>
                //
                //            <!-- JDOM - http://www.jdom.org/ -->
                //            <dependency>
                //            <groupId>org.jdom</groupId>
                //            <artifactId>jdom2</artifactId>
                //            <version>${jdom2.version}</version>
                //            </dependency>
                //
                //            <!-- Java Expression Parser - https://github.com/scijava/jep -->
                //            <dependency>
                //            <groupId>org.scijava</groupId>
                //            <artifactId>jep</artifactId>
                //            <version>${jep.version}</version>
                //            </dependency>
                //
                //            <!-- Jetty - http://eclipse.org/jetty/ -->
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-annotations</artifactId>
                //            <version>${jetty-annotations.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-client</artifactId>
                //            <version>${jetty-client.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-continuation</artifactId>
                //            <version>${jetty-continuation.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-deploy</artifactId>
                //            <version>${jetty-deploy.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-http</artifactId>
                //            <version>${jetty-http.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-http-spi</artifactId>
                //            <version>${jetty-http-spi.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-io</artifactId>
                //            <version>${jetty-io.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-jaas</artifactId>
                //            <version>${jetty-jaas.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-jaspi</artifactId>
                //            <version>${jetty-jaspi.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-jmx</artifactId>
                //            <version>${jetty-jmx.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-jndi</artifactId>
                //            <version>${jetty-jndi.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-nosql</artifactId>
                //            <version>${jetty-nosql.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-plus</artifactId>
                //            <version>${jetty-plus.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-proxy</artifactId>
                //            <version>${jetty-proxy.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-rewrite</artifactId>
                //            <version>${jetty-rewrite.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-security</artifactId>
                //            <version>${jetty-security.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-server</artifactId>
                //            <version>${jetty-server.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-servlet</artifactId>
                //            <version>${jetty-servlet.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-servlets</artifactId>
                //            <version>${jetty-servlets.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-spring</artifactId>
                //            <version>${jetty-spring.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-start</artifactId>
                //            <version>${jetty-start.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-util</artifactId>
                //            <version>${jetty-util.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-util-ajax</artifactId>
                //            <version>${jetty-util-ajax.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-webapp</artifactId>
                //            <version>${jetty-webapp.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.eclipse.jetty</groupId>
                //            <artifactId>jetty-xml</artifactId>
                //            <version>${jetty-xml.version}</version>
                //            </dependency>
                //
                //            <!-- JFreeChart - http://www.jfree.org/jfreechart/ -->
                //            <dependency>
                //            <groupId>org.jfree</groupId>
                //            <artifactId>jfreechart</artifactId>
                //            <version>${jfreechart.version}</version>
                //            <exclusions>
                //            <exclusion>
                //            <groupId>xml-apis</groupId>
                //            <artifactId>xml-apis</artifactId>
                //            </exclusion>
                //            </exclusions>
                //            </dependency>
                //
                //            <!-- JFreeSVG - http://www.jfree.org/jfreesvg/ -->
                //            <dependency>
                //            <groupId>org.jfree</groupId>
                //            <artifactId>jfreesvg</artifactId>
                //            <version>${jfreesvg.version}</version>
                //            </dependency>
                //
                //            <!-- JGraphT - https://github.com/jgrapht/jgrapht -->
                //            <dependency>
                //            <groupId>org.jgrapht</groupId>
                //            <artifactId>jgrapht-core</artifactId>
                //            <version>${jgrapht-core.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jgrapht</groupId>
                //            <artifactId>jgrapht-demo</artifactId>
                //            <version>${jgrapht-demo.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jgrapht</groupId>
                //            <artifactId>jgrapht-ext</artifactId>
                //            <version>${jgrapht-ext.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jgrapht</groupId>
                //            <artifactId>jgrapht-guava</artifactId>
                //            <version>${jgrapht-guava.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jgrapht</groupId>
                //            <artifactId>jgrapht-io</artifactId>
                //            <version>${jgrapht-io.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jgrapht</groupId>
                //            <artifactId>jgrapht-opt</artifactId>
                //            <version>${jgrapht-opt.version}</version>
                //            </dependency>
                //
                //            <!-- JGraphX - https://github.com/jgraph/jgraphx -->
                //            <dependency>
                //            <groupId>com.github.vlsi.mxgraph</groupId>
                //            <artifactId>jgraphx</artifactId>
                //            <version>${jgraphx.version}</version>
                //            </dependency>
                //
                //            <!-- JHDF5 - https://wiki-bsse.ethz.ch/label/JHDF5/hdf5 -->
                //            <dependency>
                //            <groupId>cisd</groupId>
                //            <artifactId>jhdf5</artifactId>
                //            <version>${jhdf5.version}</version>
                //            </dependency>
                //
                //            <!-- JNA - https://github.com/twall/jna -->
                //            <dependency>
                //            <groupId>net.java.dev.jna</groupId>
                //            <artifactId>jna</artifactId>
                //            <version>${jna.version}</version>
                //            </dependency>
                //
                //            <!-- Joda-Time - http://www.joda.org/joda-time/ -->
                //            <dependency>
                //            <groupId>joda-time</groupId>
                //            <artifactId>joda-time</artifactId>
                //            <version>${joda-time.version}</version>
                //            </dependency>


                // JOGL - https: //jogamp.org/jogl/
                create("jogamp").apply {
                    val version = "2.3.2"
                    alias("gluegen").to("org.jogamp.gluegen:gluegen-rt-main:$version")
                    alias("joal").to("org.jogamp.joal:joal-main:$version")
                    alias("jocl").to("org.jogamp.jocl:jocl-main:$version")
                    alias("jogl").to("org.jogamp.jogl:jogl-all-main:$version")
                }

                // JOML - http://joml-ci.github.io/JOML/
                alias("joml").to("org.joml:joml:1.9.25")

                //            <!-- JPedal - http://jpedal.org/ (defunct) -->
                //            <dependency>
                //            <groupId>org.jpedal</groupId>
                //            <artifactId>jpedalSTD</artifactId>
                //            <version>${jpedalSTD.version}</version>
                //            </dependency>
                //
                //            <!-- JSch - http://www.jcraft.com/jsch/ -->
                //            <dependency>
                //            <groupId>com.jcraft</groupId>
                //            <artifactId>jsch</artifactId>
                //            <version>${jsch.version}</version>
                //            </dependency>
                //
                //            <!-- Jython - https://jython.org/ -->
                //            <dependency>
                //            <groupId>org.python</groupId>
                //            <artifactId>jython-slim</artifactId>
                //            <version>${jython-slim.version}</version>
                //            </dependency>
                //
                //            <!-- JZlib - http://www.jcraft.com/jzlib/ -->
                //            <dependency>
                //            <groupId>com.jcraft</groupId>
                //            <artifactId>jzlib</artifactId>
                //            <version>${jzlib.version}</version>
                //            </dependency>
                //
                //            <!-- Kotlin - https://kotlinlang.org/ -->
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-compiler-embeddable</artifactId>
                //            <version>${kotlin-compiler-embeddable.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-daemon-embeddable</artifactId>
                //            <version>${kotlin-daemon-embeddable.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-reflect</artifactId>
                //            <version>${kotlin-reflect.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-script-runtime</artifactId>
                //            <version>${kotlin-script-runtime.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-script-util</artifactId>
                //            <version>${kotlin-script-util.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-scripting-common</artifactId>
                //            <version>${kotlin-scripting-common.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-scripting-compiler-embeddable</artifactId>
                //            <version>${kotlin-scripting-compiler-embeddable.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-scripting-jvm</artifactId>
                //            <version>${kotlin-scripting-jvm.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-stdlib</artifactId>
                //            <version>${kotlin-stdlib.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-stdlib-common</artifactId>
                //            <version>${kotlin-stdlib-common.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.jetbrains.kotlin</groupId>
                //            <artifactId>kotlin-stdlib-jdk8</artifactId>
                //            <version>${kotlin-stdlib-jdk8.version}</version>
                //            </dependency>
                //
                //            <!-- Logback - http://logback.qos.ch/ -->
                //            <dependency>
                //            <groupId>ch.qos.logback</groupId>
                //            <artifactId>logback-classic</artifactId>
                //            <version>${logback-classic.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>ch.qos.logback</groupId>
                //            <artifactId>logback-core</artifactId>
                //            <version>${logback-core.version}</version>
                //            </dependency>
                //
                //            <!-- LZ4 compression for Java - https://github.com/lz4/lz4-java -->
                //            <dependency>
                //            <groupId>org.lz4</groupId>
                //            <artifactId>lz4-java</artifactId>
                //            <version>${lz4-java.version}</version>
                //            </dependency>
                //
                //            <!-- MapDB - http://www.mapdb.org/ -->
                //            <dependency>
                //            <groupId>org.mapdb</groupId>
                //            <artifactId>mapdb</artifactId>
                //            <version>${mapdb.version}</version>
                //            <exclusions>
                //            <exclusion>
                //            <!--
                //        Conflicts with org.lz4:lz4-java.
                //            You may need to add it to your deps.
                //            -->
                //            <groupId>net.jpountz.lz4</groupId>
                //            <artifactId>lz4</artifactId>
                //            </exclusion>
                //            </exclusions>
                //            </dependency>
                //
                //            <!-- MigLayout - http://www.miglayout.com/ -->
                //            <dependency>
                //            <groupId>com.miglayout</groupId>
                //            <artifactId>miglayout-core</artifactId>
                //            <version>${miglayout-core.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>com.miglayout</groupId>
                //            <artifactId>miglayout-swing</artifactId>
                //            <version>${miglayout-swing.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>com.miglayout</groupId>
                //            <artifactId>miglayout-swt</artifactId>
                //            <version>${miglayout-swt.version}</version>
                //            </dependency>
                //
                //            <!-- Mines JTK - https://github.com/dhale/jtk -->
                //            <dependency>
                //            <groupId>edu.mines</groupId>
                //            <artifactId>mines-jtk</artifactId>
                //            <version>${mines-jtk.version}</version>
                //            </dependency>
                //
                //            <!-- oj! Algorithms - https://github.com/optimatika/ojAlgo -->
                //            <dependency>
                //            <groupId>org.ojalgo</groupId>
                //            <artifactId>ojalgo</artifactId>
                //            <version>${ojalgo.version}</version>
                //            </dependency>
                //
                //            <!-- OpenCSV - http://opencsv.sourceforge.net/ -->
                //            <dependency>
                //            <groupId>com.opencsv</groupId>
                //            <artifactId>opencsv</artifactId>
                //            <version>${opencsv.version}</version>
                //            </dependency>
                //
                //            <!-- picocli - http://picocli.info/ -->
                //            <dependency>
                //            <groupId>info.picocli</groupId>
                //            <artifactId>picocli</artifactId>
                //            <version>${picocli.version}</version>
                //            </dependency>
                //
                //            <!-- PostgreSQL JDBC Driver - https://jdbc.postgresql.org/ -->
                //            <dependency>
                //            <groupId>org.postgresql</groupId>
                //            <artifactId>postgresql</artifactId>
                //            <version>${postgresql.version}</version>
                //            </dependency>
                //
                //            <!-- RSyntaxTextArea - http://bobbylight.github.io/RSyntaxTextArea/ -->
                //            <dependency>
                //            <groupId>com.fifesoft</groupId>
                //            <artifactId>rsyntaxtextarea</artifactId>
                //            <version>${rsyntaxtextarea.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>com.fifesoft</groupId>
                //            <artifactId>autocomplete</artifactId>
                //            <version>${autocomplete.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>com.fifesoft</groupId>
                //            <artifactId>languagesupport</artifactId>
                //            <version>${languagesupport.version}</version>
                //            </dependency>

                // SLF4J - http://slf4j.org/
                create("slf4j").apply {
                    val version = "1.7.30"
                    alias("api").to("org.slf4j:slf4j-api:$version")
                    alias("ext").to("org.slf4j:slf4j-ext:$version")
                    alias("jcl").to("org.slf4j:slf4j-jcl:$version")
                    alias("jdk14").to("org.slf4j:slf4j-jdk14:$version")
                    alias("nop").to("org.slf4j:slf4j-nop:$version")
                    alias("simple").to("org.slf4j:slf4j-simple:$version")
                    alias("jclOverSlf4j").to("org.slf4j:jcl-over-slf4j:$version")
                }

                //            <!-- SnakeYAML - https://bitbucket.org/asomov/snakeyaml -->
                //            <dependency>
                //            <groupId>org.yaml</groupId>
                //            <artifactId>snakeyaml</artifactId>
                //            <version>${snakeyaml.version}</version>
                //            </dependency>
                //
                //            <!-- SnakeYAML Engine - https://bitbucket.org/asomov/snakeyaml-engine -->
                //            <dependency>
                //            <groupId>org.snakeyaml</groupId>
                //            <artifactId>snakeyaml-engine</artifactId>
                //            <version>${snakeyaml-engine.version}</version>
                //            </dependency>
                //
                //            <!-- Spring - https://spring.io/ -->
                //            <dependency>
                //            <groupId>org.springframework</groupId>
                //            <artifactId>spring-aop</artifactId>
                //            <version>${spring-aop.version}</version>
                //            </dependency>
                //
                //            <!-- TensorFlow - https://www.tensorflow.org/ -->
                //            <dependency>
                //            <groupId>org.tensorflow</groupId>
                //            <artifactId>tensorflow</artifactId>
                //            <version>${tensorflow.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.tensorflow</groupId>
                //            <artifactId>libtensorflow</artifactId>
                //            <version>${libtensorflow.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.tensorflow</groupId>
                //            <artifactId>libtensorflow_jni</artifactId>
                //            <version>${libtensorflow_jni.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.tensorflow</groupId>
                //            <artifactId>libtensorflow_jni_gpu</artifactId>
                //            <version>${libtensorflow_jni_gpu.version}</version>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.tensorflow</groupId>
                //            <artifactId>proto</artifactId>
                //            <version>${proto.version}</version>
                //            </dependency>
                //
                //            <!-- Trove - http://trove.starlight-systems.com/ -->
                //            <dependency>
                //            <groupId>net.sf.trove4j</groupId>
                //            <artifactId>trove4j</artifactId>
                //            <version>${trove4j.version}</version>
                //            </dependency>
                //
                //            <!-- Weka - http://www.cs.waikato.ac.nz/ml/weka/ -->
                //            <dependency>
                //            <groupId>nz.ac.waikato.cms.weka</groupId>
                //            <artifactId>weka-dev</artifactId>
                //            <version>${weka-dev.version}</version>
                //            <exclusions>
                //            <exclusion>
                //            <groupId>com.github.fommil.netlib</groupId>
                //            <artifactId>all</artifactId>
                //            </exclusion>
                //            <exclusion>
                //            <!-- Conflicts with com.github.vbmacher:java-cup -->
                //            <groupId>com.github.vbmacher</groupId>
                //            <artifactId>java-cup-runtime</artifactId>
                //            </exclusion>
                //            <exclusion>
                //            <groupId>com.googlecode.netlib-java</groupId>
                //            <artifactId>netlib-java</artifactId>
                //            </exclusion>
                //            <exclusion>
                //            <groupId>nz.ac.waikato.cms.weka.thirdparty</groupId>
                //            <artifactId>java-cup-11b</artifactId>
                //            </exclusion>
                //            <exclusion>
                //            <groupId>nz.ac.waikato.cms.weka.thirdparty</groupId>
                //            <artifactId>java-cup-11b-runtime</artifactId>
                //            </exclusion>
                //            <exclusion>
                //            <groupId>net.sourceforge.f2j</groupId>
                //            <artifactId>arpack_combined_all</artifactId>
                //            </exclusion>
                //            </exclusions>
                //            </dependency>
                //
                //            <!-- XZ for Java - https://tukaani.org/xz/java.html -->
                //            <dependency>
                //            <groupId>org.tukaani</groupId>
                //            <artifactId>xz</artifactId>
                //            <version>${xz.version}</version>
                //            </dependency>
                //
                //            <!-- Test scope dependencies -->

                // JUnit 4 - https://junit.org/junit4/
                alias("junit").to("junit:junit:4.13")

                //            <!-- JUnit 5 - https://junit.org/junit5/ -->
                //            <dependency>
                //            <groupId>org.junit.jupiter</groupId>
                //            <artifactId>junit-jupiter-api</artifactId>
                //            <version>${junit-jupiter-api.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.junit.jupiter</groupId>
                //            <artifactId>junit-jupiter-engine</artifactId>
                //            <version>${junit-jupiter-engine.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.junit.jupiter</groupId>
                //            <artifactId>junit-jupiter-migrationsupport</artifactId>
                //            <version>${junit-jupiter-migrationsupport.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.junit.jupiter</groupId>
                //            <artifactId>junit-jupiter-params</artifactId>
                //            <version>${junit-jupiter-params.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.junit.vintage</groupId>
                //            <artifactId>junit-vintage-engine</artifactId>
                //            <version>${junit-vintage-engine.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //
                //
                //            <!-- JMockit - https://jmockit.github.io/ -->
                //            <dependency>
                //            <groupId>org.jmockit</groupId>
                //            <artifactId>jmockit</artifactId>
                //            <version>${jmockit.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //
                //            <!-- Mockito - http://site.mockito.org/ -->
                //            <dependency>
                //            <groupId>org.mockito</groupId>
                //            <artifactId>mockito-core</artifactId>
                //            <version>${mockito-core.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //
                //            <!-- JMH - http://openjdk.java.net/projects/code-tools/jmh/ -->
                //            <dependency>
                //            <groupId>org.openjdk.jmh</groupId>
                //            <artifactId>jmh-core</artifactId>
                //            <version>${jmh-core.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //            <dependency>
                //            <groupId>org.openjdk.jmh</groupId>
                //            <artifactId>jmh-generator-annprocess</artifactId>
                //            <version>${jmh-generator-annprocess.version}</version>
                //            <scope>test</scope>
                //            </dependency>
                //            </dependencies>
                //            </dependencyManagement>
            }
        }
    }
}
