/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sciJava

import addGeneratedCatalog
import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

class SciJavaCatalogPlugin : Plugin<Settings> {

    override fun apply(settings: Settings) {

        settings.dependencyResolutionManagement.versionCatalogs.addGeneratedCatalog()
    }
}
